---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'new features, release notes, enhancements, what"s new' 
summary: NetApp在Keystone STaaS 服務的每個版本中都為您提供了新的和增強的功能。 
---
= Keystone STaaS 的新功能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
了解Keystone STaaS 服務的最新功能和增強功能。



[[20-july-2026]]
== 2026年7月20日

NetApp Console中Keystone儀表板的新增強功能：



[[view-subscription-expiry-and-auto-renewal-status]]
=== 查看訂閱到期日和自動續訂狀態

訂閱表格（「儲存設備 > Keystone > 訂閱」）中的「訂閱到期天數」欄現在會在到期日旁邊顯示一個圖示。如果自動續約已關閉，圖示顏色會指示到期臨近程度：綠色（>120 天）、橘色（91–120 天）、紅色（<90 天）或灰色（已過期）。對於已啟用自動續約的訂閱，會顯示自動續約圖示，表示訂閱將在當前期限結束時自動續約。此狀態為唯讀，並反映您的合約條款。開啟訂閱後，這些圖示會出現在「目前使用情況」、「使用趨勢」、「訂閱時間軸」和「資產」標籤的訂閱詳情標題中，讓您在瀏覽時可掌握到期與續約狀態的可見度。

若要深入瞭解，請參閱  https://docs.netapp.com/us-en/keystone-staas/integrations/subscriptions-tab.html["查看您的Keystone訂閱的詳細信息"]。



[[29-june-2026]]
== 2026 年 6 月 29 日

NetApp Console中Keystone儀表板的新增強功能：



[[view-adp-license-distribution-for-metrocluster-subscriptions]]
=== 查看 MetroCluster 訂閱的 ADP 授權分發狀況

「進階資料保護 (ADP)」標籤中新增了「授權分發」子選項卡，讓您可以查看 MetroCluster 合作夥伴叢集的 ADP 授權使用情況。若要深入瞭解，請參閱 link:./integrations/adp-tab.html["查看您的 Keystone MetroCluster 訂閱的使用與健康狀況"]。



[[view-ransomware-protection-status-for-your-volumes]]
=== 檢視磁碟區的勒索軟體防護狀態

「資產」中的「叢集中的磁碟區」標籤現在包含一個「ARP 狀態」欄，該欄顯示每個磁碟區是否啟用或停用自主勒索軟體防護 (ARP)，讓您了解受管資產的勒索軟體防護狀況。若要深入瞭解 ARP，請參閱 link:https://docs.netapp.com/us-en/ontap/anti-ransomware/["ONTAP 中的自主勒索軟體防護 (ARP)"]。



[[share-feedback-using-the-feedback-tab]]
=== 使用「回饋」標籤分享回饋

現在，您可以使用 Keystone 控制面板中位於螢幕右下角的全新「回饋」索引標籤，從任何螢幕提供回饋。點擊該索引標籤將開啟一個面板，您可以在其中分享您的體驗並直接向 NetApp 提交意見。



[[improve-alerting-for-capacity-usage-and-subscription-expiration]]
=== 改善容量使用情況和訂閱到期提醒

系統產生的監控器現在可針對容量使用情況和訂閱到期情況提供更精細的警示。

訂閱到期提醒現在會在到期前五個門檻觸發：到期前 180 天、90 天、60 天、30 天和 7 天，嚴重程度會隨著到期日的臨近而從通知等級升級到緊急等級。

對於容量使用情況，突發警報閾值現在基於您訂閱的承諾突發百分比，而不是固定的 20%。例如，如果您的承諾突發百分比為 40%，則當承諾容量利用率達到 140% 時，將觸發嚴重警報。

如需深入瞭解，請參閱link:./integrations/monitoring-alert-monitors.html["查看並建立Keystone訂閱的警報監視器"]。



[[25-may-2026]]
== 2026 年 5 月 25 日

NetApp Console中Keystone儀表板的新增強功能：



[[improved-display-of-multiple-updates-on-the-same-day-in-the-subscription-timeline]]
=== 改進了訂閱時間軸中同一天多次更新的顯示方式

訂閱時間軸圖表現在會在同一天發生多個不同類型的訂閱更新時顯示一個數字，而不是顯示單獨的圖示。將滑鼠懸停在該數字上即可查看當天所有更新類型。下載的報告包含每個更新的單獨行，為您提供所有變更的完整記錄。要了解更多信息，請參閱 link:./integrations/subscription-timeline.html["查看Keystone訂閱的時間表"]。



[[27-april-2026]]
== 2026 年 4 月 27 日

NetApp Console中Keystone儀表板的新增強功能：



[[renamed-provisioned-capacity-label]]
=== 重新命名已佈建容量標籤

標籤 *Provisioned capacity* 已重新命名為 *Provisioned volume capacity*。更新後的標籤也已反映在相關的 CSV 和 Excel 報表中。



[[forecast-toggle-for-accrued-burst]]
=== 累積高載的預測切換

您現在可以在 *Consumption trend* 標籤的 *Accrued burst* 檢視中使用 *Forecast* 切換按鈕，預測從目前日期起未來 120 天的累積突發流量使用量。要了解更多資訊，請參閱 link:./integrations/consumption-tab.html#view-forecast-data["檢視預測資料"]。



[[30-march-2026]]
== 2026 年 3 月 30 日

NetApp Console中Keystone儀表板的新增強功能：



[[above-burst-capacity-on-the-historical-consumption-chart]]
=== 歷史使用量圖表上高於突發容量

*消耗趨勢* 標籤中的歷史消耗圖表現在會突顯超出突發限制的使用量。若要深入瞭解、請參閱 link:./integrations/consumption-tab.html["查看Keystone訂閱的消費趨勢"]。



[[forecast-for-capacity-usage]]
=== 容量使用預測

您可以使用 *Consumption trend* 標籤的 *Historical consumption* 檢視中的 *Forecast* 切換功能，預測從目前日期起未來 120 天的容量使用量。如需深入瞭解、請參閱 link:./integrations/consumption-tab.html#view-forecast-data["檢視預測資料"]。



[[tracking-id-in-subscription-export]]
=== 訂閱匯出中的追蹤 ID

現在，從 *Subscriptions* 頁面下載的訂閱報告在 Excel 和 CSV 格式的效能服務等級資料中包含了 *Tracking ID*。



[[subscriptions-page-column-visibility-updates]]
=== 訂閱頁面欄可見性更新

在「訂閱」頁面上、「Keystone 版本」欄現在預設為隱藏、而「連結的訂閱」欄僅在有連結的訂閱可用時才會顯示。



[[march-02-2026]]
== 2026 年 3 月 2 日

NetApp Console中Keystone儀表板的新增強功能：



[[new-columns-in-the-volumes-in-clusters-tab]]
=== 叢集中的磁碟區標籤中的新欄

在「資產」的「叢集中的磁碟區」標籤中新增了三個欄位：*Hot data*、*Cold tier (%)*和*Hot tier (%)*。如需深入瞭解，請參閱 link:./integrations/assets-tab.html["查看與Keystone訂閱相關的資產"] 和 link:./integrations/assets.html["查看Keystone訂閱中的資產"]。



[[invoiced-uninvoiced-and-provisional-burst-usage-in-consumption-trend]]
=== 消費趨勢中的已開立發票、未開立發票和暫定突發使用量

*用量趨勢* 標籤中的累積突發計費圖表現在顯示已開立發票、未開立發票和暫定突發用量。如需深入瞭解，請參閱 link:./integrations/consumption-tab.html#view-accrued-burst["查看累計突發事件"]。



[[enhancements-to-the-monitoring-view]]
=== 監控檢視的增強功能

*監控* 視圖包含以下更新：

* *Alerts 標籤*：*Alert* 欄已重新命名為 *Alert type & condition*。現在您也可以使用 *Status* 欄旁的省略號圖示來編輯警報、新增備註或查看警報詳細資料。
* *Alert monitors tab*：*Condition* 列已重新命名為 *Monitor type & condition*。


如需深入瞭解，請參閱 link:./integrations/monitoring-alerts.html["查看並管理Keystone訂閱的提醒"] 和 link:./integrations/monitoring-alert-monitors.html["查看並建立Keystone訂閱的警報監視器"]。



[[16-february-2026]]
== 2026 年 2 月 16 日

NetApp Console中Keystone儀表板的新增強功能：



[[dii-add-on-consumption-display]]
=== Data Infrastructure Insights 附加消耗顯示器

Data Infrastructure Insights （ DII ） 附加元件使用量現在會顯示在 *目前使用量* 和 *使用量趨勢* 標籤中。若要深入瞭解、請參閱 link:./concepts/data-infra-insights.html#view-dii-consumption["查看 DII 消費狀況"]。



[[02-february-2026]]
== 2026 年 2 月 02 日

NetApp Console中Keystone儀表板的新增強功能：



[[interactive-filtering-for-daily-accrued-burst-data]]
=== 每日累積突發資料的互動式篩選

「消費趨勢」標籤中的「按天計算累積峰值」表格現已支援互動式篩選。選擇累計峰值計費圖表中的任一長條圖，即可僅查看該計費週期內的天數。要了解更多信息，請參閱link:./integrations/consumption-tab.html#view-daily-accrued-burst-data-usage["查看每日累計突發資料使用量"]。



[[enhanced-date-range-display-in-accrued-burst-graph]]
=== 增強了累計突發圖表中的日期範圍顯示

*消費趨勢* 標籤中的累積突發帳單圖表現在顯示每個帳單週期的完整日期範圍，例如 Oct 01, 2025 to Oct 31, 2025，而不僅僅是月份和年份。



[[expandable-subscription-details-view]]
=== 可展開的訂閱詳細資料檢視

*訂閱*標籤包含一個選項，可以展開所有訂閱並同時查看每個訂閱的效能服務等級資訊。要了解更多信息，請參閱link:./integrations/subscriptions-tab.html["查看您的Keystone訂閱的詳細信息"]。



[[new-usage-type-column]]
=== 新增使用類型欄

*訂閱* 標籤包含一個 *使用類型* 欄，該欄顯示訂閱是按已佈建、實體或邏輯使用量計費。要了解更多信息，請參閱link:./integrations/subscriptions-tab.html["查看您的Keystone訂閱的詳細信息"]。



[[08-december-2025]]
== 2025年12月8日

NetApp Console中Keystone儀表板的新增強功能：



[[renamed-accrued-burst-capacity-label]]
=== 更名為「累積突發容量」標籤

標籤「累計突發容量」更名為「累計突發」。



[[24-november-2025]]
== 2025年11月24日

NetApp Console中Keystone儀表板的新增強功能：



[[tracking-id-for-coverage-gap-subscriptions]]
=== 用於追蹤保障缺口訂閱的 ID

在「監控 > 警報監控」上的「完成您的保障」通知框中，現在每個訂閱都會在訂閱編號旁顯示其追蹤 ID。



[[10-november-2025]]
== 2025年11月10日

NetApp Console中Keystone儀表板的新增強功能：



[[complete-your-coverage-notification-box]]
=== 填寫您的保險覆蓋範圍通知框

「監控」頁面上的「警報監控」標籤包含一個「完善您的覆蓋範圍」通知框，當存在覆蓋範圍缺口時，該通知框就會出現。此框列出了缺少容量或到期監控器的訂閱，以及沒有訂閱的監控器。您可以透過向現有監視器新增訂閱、建立新監視器或刪除未使用的監視器來彌補這些差距。欲了解更多信息，請參閱 link:https://docs.netapp.com/us-en/keystone-staas/integrations/monitoring-alert-monitors.html#manage-coverage-gaps["管理警報監控器的覆蓋範圍缺口"]。



[[13-october-2025]]
== 2025年10月13日

NetApp Console中Keystone儀表板的新增強功能：



[[qos-policy-override-column-in-assets-tab]]
=== 資產標籤中的 QoS 策略覆蓋列

*Assets* 選項卡中的 *Volumes in clusters* 選項卡現在包含一個 *QoS policy override* 列，指示是否繞過備份和鏡像卷的 QoS 規則，顯示 *true*（忽略規則）、*false*（強制執行規則）或 *N/A*（對於鏡像卷）。


NOTE: 對於Keystone v3 訂閱，此列顯示 *N/A*，因為 QoS 策略不適用於 v3 產品。



[[enhanced-alerts-visibility-in-overview-page]]
=== 增強了概覽頁面中的警報可見性

*概覽*頁面現在包括兩個新的警報部分，名為*按嚴重程度排列的未解決警報*和*最早未解決的Keystone警報*。要了解更多信息，請參閱link:https://docs.netapp.com/us-en/keystone-staas/integrations/keystone-console.html["NetApp控制台中的Keystone儀表板"]。



[[06-october-2025]]
== 2025年10月6日



[[bluexp-is-now-netapp-console]]
=== BlueXP現在是NetApp控制台

NetApp控制台建立在增強和重組的BlueXP基礎之上，可在企業級內部和雲端環境中集中管理NetApp儲存和NetApp資料服務，提供即時洞察、更快的工作流程和簡化的管理，並且高度安全且合規。

有關更改的詳細信息，請參閱link:https://docs.netapp.com/us-en/bluexp-relnotes/index.html["NetApp控制台發行說明"^]。



[[22-september-2025]]
== 2025年9月22日



[[addition-of-alert-monitoring]]
=== 增加警報監控

BlueXP中的Keystone儀表板現在包括一個「監控」選項卡，用於管理您訂閱中的警報和監視器。此新選項卡使您能夠：

* 查看和解決活動警報，包括系統產生的和使用者定義的容量使用情況和訂閱到期警報。
* 建立警報監視器來追蹤容量使用情況和訂閱到期事件。


要了解更多信息，請參閱link:https://docs.netapp.com/us-en/keystone-staas-2/integrations/monitoring-alerts.html["查看和管理警報和監視器"]。



[[streamlined-performance-service-levels-viewing]]
=== 簡化的效能服務等級查看

您可以在“*訂閱*”選項卡中查看性能服務級別信息，現在該信息已從單獨的選項卡移至可擴展視圖。按一下「到期日」欄位旁的向下箭頭可查看每個訂閱的到期日。要了解更多信息，請參閱link:https://docs.netapp.com/us-en/keystone-staas-2/integrations/subscriptions-tab.html["查看您的Keystone訂閱的詳細信息"]。



[[28-august-2025]]
== 2025年8月28日



[[enhanced-logical-usage-tracking-with-a-new-column]]
=== 使用新列增強邏輯使用情況跟踪

新增了新欄位“總佔用空間”，以增強對FabricPool磁碟區的Keystone消耗追蹤：

* * BlueXP中的Keystone儀表板 *：您可以在 *Assets* 標籤中的 *Volumes in clusters* 標籤中看到 *Total footprint* 列。
* *Digital Advisor*：您可以在 *磁碟區和物件* 標籤中的 *磁碟區詳細資料* 標籤中看到 *總足跡* 欄位。


此列顯示使用FabricPool分層的磁碟區的總邏輯佔用空間，包括效能層和冷層的數據，因此您可以精確計算Keystone消耗。



[[05-august-2025]]
== 2025年8月5日



[[view-instance-level-consumption-data]]
=== 查看實例層級消耗數據

您可以透過BlueXP中的Keystone儀表板查看每個效能服務等級實例的目前消耗和歷史資料。如果您擁有Keystone版本 3 (v3) 訂閱，此功能適用於具有多個執行個體的效能服務等級。要了解更多信息，請參閱link:https://docs.netapp.com/us-en/keystone-staas/integrations/current-usage-tab.html["查看Keystone訂閱的消耗量"]。



[[30-june-2025]]
== 2025年6月30日



[[keystone-version-3-v3-release]]
=== Keystone版本 3 (v3) 發布

現在您可以訂閱Keystone版本 3 (v3)，這是NetApp Keystone STaaS 產品的最新版本。此版本引入了多項增強功能，包括簡化的效能服務等級、額外的突發容量選項和靈活的計費頻率。這些改進簡化了儲存解決方案的管理、最佳化和擴充。要了解更多信息，請參閱link:https://docs.netapp.com/us-en/keystone-staas/concepts/metrics.html["v3 的Keystone STaaS 服務"]。

您可以聯絡Keystone支援團隊訂閱Keystone版本 3 (v3)。更多詳情請參閱 link:https://docs.netapp.com/us-en/keystone-staas/concepts/support-services.html["取得有關Keystone的協助"]。



[[19-june-2025]]
== 2025年6月19日



[[keystone-dashboard-in-bluexp]]
=== BlueXP中的Keystone儀表板

現在您可以直接從BlueXP存取Keystone儀表板。透過此集成，您可以從一個地方監控、管理和追蹤所有Keystone訂閱以及其他NetApp服務。

使用BlueXP中的Keystone儀表板，您可以：

* 在一個地方查看所有訂閱詳細資訊、容量使用情況和資產。
* 輕鬆管理訂閱並隨著需求的變化請求更改。
* 隨時了解有關您的儲存環境的最新資訊。


首先，前往BlueXP左側導覽功能表中的 *儲存 > Keystone *。要了解更多信息，請參閱link:https://docs.netapp.com/us-en/keystone-staas/integrations/dashboard-overview.html["Keystone儀表板概述"]。



[[08-january-2025]]
== 2025年1月8日



[[addition-of-daily-accrued-data-usage-viewing-options]]
=== 增加每日累計資料使用量檢視選項

現在，您可以透過點擊顯示發票資料的欄，以圖表或表格形式查看每月或每季計費期間的每日累積突發資料使用情況。要了解更多信息，請參閱link:./integrations/consumption-tab.html#view-daily-accrued-burst-data-usage["查看每日累計突發資料使用量"]。



[[12-december-2024]]
== 2024年12月12日



[[renamed-logical-used-column]]
=== 重新命名“邏輯使用”列

*Volumes & Objects* 中的 *Volume Details* 標籤中的 *Logical Used* 資料列現已重新命名為 * Keystone Logical Used*。



[[enhanced-assets-tab]]
=== 增強資產選項卡

* Keystone Subscriptions* 畫面中的 *Assets* 選項卡現在有兩個新的子選項卡：* ONTAP* 和 * StorageGRID*。這些子選項卡根據您的訂閱提供ONTAP 的詳細集群層級見解和StorageGRID的網格層級資訊。要了解更多信息，請參閱link:./integrations/assets-tab.html["資產選項卡"^]。



[[new-hideshow-columns-option]]
=== 新的隱藏/顯示列選項

*Volumes & Objects* 中的 *Volume Details* 選項卡現在包含 *Hide/Show Columns* 選項。此選項使您能夠選擇或取消選擇列，以根據您的喜好自訂磁碟區的表格清單。要了解更多信息，請參閱link:./integrations/volumes-objects-tab.html["體積和物件選項卡"^]。



[[21-november-2024]]
== 2024年11月21日



[[enhanced-invoiced-accrued-burst]]
=== 增強型發票應計突發

如果您選擇了按季度計費，現在可以透過「已開立發票的累計突發」選項按季度查看累計突發使用資料。要了解更多信息，請參閱link:./integrations/consumption-tab.html#view-accrued-burst["查看已開票的累計突發"^]。



[[new-columns-in-the-volumes-details-tab]]
=== 「卷宗詳細資料」標籤中的新列

為了提高計算邏輯使用情況的清晰度，在「*磁碟區和物件*」標籤中的「*磁碟區詳細資料*」標籤中新增了兩個新欄位：

* *邏輯 AFS*：顯示磁碟區的活動檔案系統所使用的邏輯容量。
* *實體快照*：顯示快照所使用的實體空間。


這些列更清楚地顯示了「邏輯已使用」列，該列顯示了磁碟區的活動檔案系統所使用的組合邏輯容量和快照所使用的實體空間。



[[11-november-2024]]
== 2024年11月11日



[[enhanced-report-generation]]
=== 增強報告生成

現在，您可以使用Digital Advisor中的報告功能產生合併報告來查看Keystone資料的詳細資訊。要了解更多信息，請參閱link:./integrations/options.html#generate-consolidated-report-from-digital-advisor["產生合併報告"^]。



[[10-july-2024]]
== 2024年7月10日



[[label-modifications]]
=== 標籤修改

標籤 *Current Usage* 改為 *Current Consumption*，*Capacity Trend* 改為 *Consumption Trend*。



[[search-bar-for-subscriptions]]
=== 訂閱的搜尋欄

* Keystone訂閱* 螢幕內所有選項卡上的 *訂閱* 下拉選單現在都包含一個搜尋列。您可以搜尋「*訂閱*」下拉式選單中列出的特定訂閱。



[[27-june-2024]]
== 2024年6月27日



[[consistent-display-of-subscription]]
=== 訂閱的一致顯示

* Keystone訂閱* 畫面已更新，以在所有分頁上顯示所選的訂閱號碼。

* 當「* Keystone訂閱*」畫面中的任何標籤刷新時，螢幕會自動導航至「*訂閱*」選項卡，並將所有選項卡重設為「*訂閱*」下拉清單中列出的第一個訂閱。
* 如果所選訂閱未訂閱效能指標，則「效能」標籤會在導覽時顯示「訂閱」下拉式功能表中列出的第一個訂閱。




[[29-may-2024]]
== 2024年5月29日



[[enhanced-burst-indicator]]
=== 增強型突發指示器

使用情況圖表索引中的 *Burst* 指示器得到增強，可以顯示突發限制百分比值。該值根據訂閱的約定突發限製而變化。您也可以將滑鼠懸停在「*訂閱*」標籤中的「*使用狀態*」欄位中的「*突發使用情況*」指示器上來查看突發限制值。



[[addition-of-service-levels]]
=== 增加服務級別

服務等級 *CVO Primary* 和 *CVO Secondary* 包括在內，以支援具有零承諾容量的費率計劃或配置了城域集群的訂閱的Cloud Volumes ONTAP 。

* 您可以從 * Keystone Subscriptions* 小工具的舊儀表板和 *Capacity Trend* 標籤查看這些服務等級的容量使用圖表，也可以從 *Current Usage* 標籤查看詳細的使用情況資訊。
* 在「訂閱」標籤中，這些服務等級顯示為 `CVO (v2)`在*使用類型*列中，允許根據這些服務等級識別計費。




[[zoom-in-feature-for-short-term-bursts]]
=== 短期爆發的放大功能

*容量趨勢*標籤現在包含放大功能，可以查看使用圖表中短期爆發的詳細資訊。有關更多信息，請參閱link:./integrations/consumption-tab.html["容量趨勢選項卡"^] 。



[[enhanced-display-of-subscriptions]]
=== 增強訂閱顯示

訂閱的預設顯示已增強，可依追蹤 ID 排序。  *訂閱*標籤中的訂閱（包括*訂閱*下拉選單和 CSV 報告中的訂閱）現在將根據追蹤 ID 的字母順序顯示，按照 a、A、b、B 等順序顯示。



[[enhanced-accrued-burst-display]]
=== 增強累計爆發顯示

當滑鼠懸停在「容量趨勢」標籤中的容量使用情況長條圖上時出現的工具提示現在會顯示基於承諾容量的累積突發類型。它區分臨時和已開票的累計突發，對於承諾容量費率計劃為零的訂閱顯示*臨時累計消耗*和*已開票累計消耗*，對於承諾容量非零的訂閱顯示*臨時累計突發*和*已開票累計突發*。



[[09-may-2024]]
== 2024年5月9日



[[new-columns-in-csv-reports]]
=== CSV 報告中的新列

*容量趨勢*選項卡中的 CSV 報告現在包括*訂閱編號*和*帳戶名稱*列，以提供更詳細的資訊。



[[enhanced-usage-type-column]]
=== 增強使用類型列

*訂閱*標籤中的*使用類型*列已增強，可以以逗號分隔的值顯示涵蓋文件和物件服務等級的訂閱的邏輯和實體使用情況。



[[access-object-storage-details-from-volume-details-tab]]
=== 從“卷詳細信息”選項卡訪問對象存儲詳細信息

*磁碟區和物件*標籤中的*磁碟區詳細資料*標籤現在提供物件儲存詳細資料以及包含檔案和物件服務等級的訂閱的磁碟區資訊。您可以點擊「卷宗詳情」標籤中的「物件儲存詳情」按鈕查看詳情。



[[28-march-2024]]
== 2024年3月28日



[[improvement-to-qos-policy-compliance-display-in-the-volume-details-tab]]
=== 改進了「卷宗詳細資料」標籤中的 QoS 策略合規性顯示

*捲和物件*標籤中的*卷詳細資料*標籤現在可以更好地查看服務品質 (QoS) 策略合規性。先前稱為 *AQoS* 的欄位重新命名為 *Compliant*，表示 QoS 策略是否符合要求。此外，還新增了一個新列*QoS 策略類型*，用於指定策略是固定的還是自適應的。如果兩者都不適用，則該列顯示「不可用」。有關更多信息，請參閱link:./integrations/volumes-objects-tab.html["體積和物件選項卡"^] 。



[[new-column-and-simplified-subscription-display-in-the-volume-summary-tab]]
=== 交易量摘要標籤中的新欄位和簡化的訂閱顯示

* *Volumes & Objects* 選項卡中的 *Volume Summary* 選項卡現在包含一個名為 *Protected* 的新欄位。此列提供與您訂閱的服務等級相關的受保護磁碟區的數量。如果您按一下受保護磁碟區的數量，它將帶您進入「磁碟區詳細資料」標籤，您可以在其中查看受保護磁碟區的篩選清單。
* 「*卷摘要*」標籤已更新，僅顯示基本訂閱，不包括附加服務。有關更多信息，請參閱link:./integrations/volumes-objects-tab.html["體積和物件選項卡"^] 。




[[change-to-accrued-burst-detail-display-in-the-capacity-trend-tab]]
=== 容量趨勢標籤中累積突發詳細資訊的顯示發生變化

將滑鼠懸停在「容量趨勢」標籤中的容量使用情況長條圖上時出現的工具提示將顯示當前月份累積突發的詳細資訊。前幾個月的詳細資訊將不會提供。



[[enhanced-access-to-view-historical-data-for-keystone-subscriptions]]
=== 增強查看Keystone訂閱歷史資料的權限

如果Keystone訂閱已修改或續訂，現在可以查看歷史資料。您可以將訂閱的開始日期設定為先前的日期以查看：

* 來自「容量趨勢」標籤的消耗和累積突發使用資料。
* 「效能」標籤中的ONTAP磁碟區的效能指標。


數據根據所選的訂閱開始日期顯示。



[[29-february-2024]]
== 2024年2月29日



[[addition-of-the-assets-tab]]
=== 新增資產選項卡

* Keystone Subscriptions* 畫面現在包括 *Assets* 選項卡。此新選項卡根據您的訂閱提供集群層級的資訊。有關更多信息，請參閱link:./integrations/assets-tab.html["資產選項卡"^] 。



[[improvements-to-the-volumes-objects-tab]]
=== 體積和物件選項卡的改進

為了更清楚地了解您的ONTAP系統卷，已在 *Volumes* 選項卡中添加了兩個新選項卡按鈕 *Volume Summary* 和 *Volume Details*。  *Volume Summary* 標籤提供與您訂閱的服務等級相關的磁碟區的總數，包括其 AQoS 合規狀態和容量資訊。 *卷詳細資料*選項卡列出了所有磁碟區及其具體資訊。有關更多信息，請參閱link:./integrations/volumes-objects-tab.html["體積和物件選項卡"^] 。



[[enhanced-search-experience-on-digital-advisor]]
=== 增強Digital Advisor的搜尋體驗

*Digital Advisor* 螢幕上的搜尋參數現在包括Keystone訂閱號和為Keystone訂閱建立的關注清單。您可以輸入訂閱號或關注清單名稱的前三個字元。有關更多信息，請參閱link:./integrations/keystone-aiq.html["在Active IQ Digital Advisor上查看Keystone儀表板"^] 。



[[view-timestamp-of-the-consumption-data]]
=== 查看消費資料的時間戳

您可以在 * Keystone Subscriptions* 小工具的舊儀表板上查看消費資料的時間戳記（以 UTC 為單位）。



[[13-february-2024]]
== 2024年2月13日



[[ability-to-view-subscriptions-linked-to-a-primary-subscription]]
=== 可以查看連結到主訂閱的訂閱

您的一些主要訂閱可以具有連結的次要訂閱。如果是這種情況，主訂閱號碼將繼續顯示在「*訂閱號碼*」欄中，而連結的訂閱號碼將在「*訂閱*」標籤上的新欄位「*連結的訂閱*」中列出。只有當您已連結訂閱時，「*連結訂閱*」列才可用，並且您可以看到有關它們的通知訊息。



[[11-january-2024]]
== 2024年1月11日



[[invoiced-data-returned-for-accrued-burst]]
=== 已回傳累計突發的發票數據

現在，*Capacity Trend* 選項卡中的 *Accrued Burst* 標籤已修改為 *Invoiced Accrued Burst*。選擇此選項，您可以查看已計費累積突發資料的每月圖表。有關更多信息，請參閱link:./integrations/consumption-tab.html#view-accrued-burst["查看已開票的累計突發"^] 。



[[accrued-consumption-details-for-specific-rate-plans]]
=== 特定費率方案的累積消費詳情

如果您訂閱的費率方案中承諾容量為_零_，您可以在「容量趨勢」標籤中查看累積消費詳情。選擇「已開立發票累積消費」選項後，您可以查看已開立的累計消費資料月表。



[[15-december-2023]]
== 2023年12月15日



[[ability-to-search-by-watchlists]]
=== 能夠按關注清單搜尋

Digital Advisor中對監控清單的支援已擴展到包括Keystone系統。現在您可以透過使用關注清單搜尋來查看多個客戶的訂閱詳細資訊。有關Keystone STaaS 中監視列表使用的更多信息，請參閱link:./integrations/keystone-aiq.html#search-by-keystone-watchlists["按Keystone關注列表搜索"^]。



[[date-converted-to-utc-timezone]]
=== 日期轉換為 UTC 時區

Digital Advisor的 * Keystone Subscriptions* 螢幕標籤上傳回的資料以 UTC 時間（伺服器時區）顯示。當您輸入日期進行查詢時，它會自動被視為 UTC 時間。有關更多信息，請參閱link:./integrations/keystone-aiq.html["Keystone訂閱儀表板和報告"^] 。
