---
sidebar: sidebar 
permalink: concepts/components.html 
keywords: infrastructure component, deployment requirement, installation requirement 
summary: 了解在您的環境中啟用NetApp Keystone STaaS 服務所需的元件。 
---
= 部署所需的元件
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
在您的環境中啟用NetApp Keystone STaaS 服務需要幾個元件。在開始之前，您應該查看有關這些組件的詳細資訊。



== 場地要求

有一些特定於站點的要求，例如空間、機架、PDU、電源和冷卻，以及這裡討論的額外網路和安全要求。



=== 空間

用於承載Keystone基礎設施設備的佔地面積（由客戶提供）。  NetApp根據最終配置提供重量規格。



=== 機架

客戶操作產品中的四個立柱架（由客戶提供）。在NetApp營運的產品中， NetApp或客戶都可以依照需求提供機架。  NetApp提供 42 個深度機架。



=== PDU

您應該提供連接到兩個獨立的、受保護的電路的配電單元 (PDU)，並配備足夠的 C13 插座。在客戶營運服務中，在某些情況下需要 C19 分行。在NetApp營運的產品中， NetApp或客戶可以根據需求提供 PDU。



=== 力量

您應該提供所需的電源。 NetApp將根據最終配置提供基於 200V 額定值（典型 A、最大 A、典型 W、最大 W、電源線類型和數量）的電源需求規格。所有組件均有冗餘電源。  NetApp將提供機櫃內電源線。



=== 冷卻

NetApp可根據最終配置和要求提供冷卻需求規格（典型 BTU、最大 BTU）。



=== 虛擬機

部署Keystone Collector 和 ITOM Collector 需要虛擬機器。有關安裝先決條件，請參閱link:../installation/installation-overview.html["Keystone Collector 安裝指南"]和link:../installation/itom-prereqs.html["ITOM Collector 的安裝要求"]。其他要求在部署期間共用。



=== 部署選項

Keystone Collector 可以透過以下方式部署：

* VMware OVA 範本（需要 VMware vCenter Server 6.7 或更高版本）
* 客戶提供在以下作業系統之一上運行的 Linux 伺服器：Debian 12、Red Hat Enterprise Linux 8.6 或更高版本 8.x，或 CentOS 7（僅適用於現有環境）。  Keystone軟體的安裝使用 `.deb`或者 `.rpm`包，取決於 Linux 發行版。


ITOM Collector 可以透過以下方式部署：

* 客戶提供運行 Debian 12、Ubuntu 20.04 LTS、Red Hat Enterprise Linux (RHEL) 8.x、Amazon Linux 2023 或更新版本的 Linux 伺服器。
* 客戶提供執行 Windows Server 2016 或更新版本的 Windows 伺服器。
+

TIP: 推薦的作業系統是 Debian 12、Windows Server 2016 或更新版本。





=== 聯網

軟體更新和使用資料上傳需要對_keystone.netapp.com_進行出站訪問，這對於Keystone Collector 和 AIOps 解決方案網關的運作和維護至關重要。

根據客戶要求和所使用的儲存控制器， NetApp可以在客戶站點提供 10 GB、40 GB 和 100 GB 的連接。

NetApp僅為NetApp提供的基礎設施設備提供所需的收發器。您應該提供客戶設備所需的收發器以及與NetApp提供的Keystone基礎架構設備連接的電纜。



== 遠端存取要求

客戶資料中心或客戶擁有的共置服務中安裝的儲存基礎架構與Keystone營運中心之間需要建立網路連線。客戶負責提供計算和虛擬機器以及互聯網服務。客戶還負責作業系統修補（非基於 OVA 的部署）和基於內部安全策略的安全強化。網路設計應基於安全協議，防火牆策略將得到NetApp和客戶的批准。

NetApp需要存取已安裝的用於監控和管理的硬體和軟體元件，以便為Keystone客戶提供監控和計費等服務。最常見的方法是建立與客戶網路的虛擬私人網路（VPN）連接並存取所需的資料。為了克服客戶認為因向新服務開放防火牆連接埠而產生的任何操作複雜性，監控工具會啟動外部連線。 NetApp雲端應用程式（例如 ITOM 監控解決方案和 Zuora）使用此連接來執行各自的服務。此方法滿足了客戶不開啟防火牆連接埠但提供對此服務的一部分的監控組件的存取的要求。
