---
sidebar: sidebar 
permalink: concepts/metrics.html 
keywords: metrics, GiB, IOPS, latency, durability, v2, version 2 
summary: NetApp Keystone STaaS 服務使用多個術語來衡量指標。在使用Keystone服務第 2 版時，您可能會想要了解更多有關這些術語的資訊。 
---
= Keystone中使用的指標和定義
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp Keystone STaaS 服務使用多個術語來衡量指標。在使用Keystone時，您可能想要了解更多有關這些術語的資訊。

Keystone STaaS 服務中使用以下術語和定義來衡量指標：

* 容量：以 GiB、TiB 和 PiB 為單位。
* IO 密度：IOPS/TiB：基於工作負載消耗的總空間，每秒處理的輸入/輸出操作數，以以太位元組為單位。
* 服務可用性
* 準確資料存取的持久性
* 延遲和速度




== 指標測量

* *以 GiB、TiB 和 PiB 為單位的容量測量*：使用 1024 為基數測量資料儲存容量（1 GiB = 1024^3^ 位元組、1 TiB = 1024^4^ 位元組和 1 PiB = 1024^5^ 位元組）。
* *IOPS/TiB 中的操作計數器圖表*：應用程式請求的每秒協定操作數除以工作負載使用的磁碟區大小。
* *可用性*：以服務成功回應的 I/O 請求數除以向服務發出的 I/O 請求總數的百分比來衡量。這是在一個月的服務劃分時測量的，不包括計劃的服務停機時間或設施、網路或客戶提供的其他服務的不可用時間。
* *耐用性*：在不損失保真度的情況下存取的資料百分比，不包括客戶造成的刪除或損壞。
* *延遲*：在服務邊界（儲存控制器 I/O 連接埠）測量從用戶端收到的 I/O 請求的服務時間。




=== 吞吐量效能指標

吞吐量效能指標僅適用於基於下列內容的檔案和區塊服務：

* 32 KB 區塊大小
* 70% 讀取/30% 寫入 I/O 組合




=== IO密度的變化

以 IOPS/TiB 和/或 MBps/TiB 計算的 IO 密度取決於以下因素：

* 工作負載特徵
* 延遲，不包括以下內容：
+
** 應用程式延遲
** 主機延遲
** 在控制器連接埠之間傳輸資料時客戶網路的延遲
** 在FabricPool的情況下，與資料傳輸到物件儲存相關的開銷延遲
** QoS 自動套用延遲，使 IO 保持在服務等級最大值範圍內


* 計入已使用容量的用戶和 Snapshot 副本數據
* 每個ONTAP磁碟區上分配的絕對最小 IOPS，無論磁碟區中的資料量為何：
+
** 極限：1,000 IOPS
** 高級：500 IOPS
** 性能、標準和價值：75 IOPS


* 在使用進階資料保護附加服務時，目標延遲僅適用於服務來自本機儲存的 IO 請求。




=== 卷 AQoS

每個ONTAP磁碟區都應套用適用的自適應服務品質 (AQoS) 策略。否則，每個未套用 AQoS 策略的磁碟區內的容量將依照最高服務等級的費率計費。
