---
sidebar: sidebar 
permalink: concepts/misc-volume-billing.html 
keywords: Billing and miscellaneous scenarios 
summary: 了解特定配置的Keystone計費，包括克隆卷、進階資料保護等。 
---
= 了解Keystone針對特定容量配置的計費方式
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
了解特定配置的Keystone計費可以幫助您最佳化服務使用並管理成本。配置包括複製磁碟區、進階資料保護、臨時磁碟區、QoS 策略、 SnapMirror目標、LUN 和系統/根磁碟區。



== 克隆卷的計費

如果在ONTAP中克隆了磁碟區並且您使用它們來備份和恢復數據，則您可以繼續使用這些克隆，而無需支付任何額外費用。但是，長期用於業務中任何其他目的的克隆卷都需要付費。

請注意以下事項：

* 只要克隆卷的大小小於父卷的 10%（克隆卷中使用的物理容量與父卷中使用的物理容量之比），克隆卷就免費。
* 克隆卷沒有 24 小時的寬限期。僅考慮克隆的大小。
* 一旦克隆卷超過父卷物理大小的 10%，克隆卷就會被視為標準卷（邏輯使用容量）。




== 高級資料保護計費

進階資料保護使用NetApp MetroCluster在兩個實體上分離的叢集之間鏡像資料。對於MetroCluster鏡像聚合，資料寫入兩次，每個叢集一次。 Keystone服務對雙方的消費進行獨立計費，從而產生兩條相同的消費記錄。附加費用適用於訂閱中的所有容量，無論資料是在來源處，還是鏡像或非鏡像資料。

每個MetroCluster站點都有自己的訂閱和計費。對於MetroCluster配置，使用情況測量考慮了兩個站點之間的儲存利用。如果您的MetroCluster設定中每個站點有 100 TiB，則每個站點上只有 50 TiB 被主動使用，而每個站點上剩餘的 50 TiB 則用作鏡像備份。高級資料保護附加費用是根據這 100 TiB 的總活動使用量計算的，並透過各自的訂閱在兩個站點之間分攤，每個站點 50 TiB。

如果您透過ONTAP系統管理員（系統管理員）或Active IQ Unified Manager（統一管理器）監控集群，您可能會發現這些工具報告的消耗量與Keystone之間存在差異。系統管理員和統一管理器不會報告鏡像（遠端）叢集上的捲，因此，報告的消耗指標僅為Keystone服務報告的消耗指標的一半。

.範例：
站點 A 和站點 B 採用MetroCluster配置進行設定。當使用者在網站 A 建立 10 TB 的磁碟區時，網站 B 中也會建立相同的 10 TB 磁碟區。 KeystoneKeystone每個站點的消耗量為 10 TB，總共增加 20 TB。系統管理員和統一管理器報告在站點 A 中建立的 10 TB 卷，但沒有報告在站點 B 中建立的 10 TB 卷。

此外，在具有進階資料保護的Keystone系統上建立的所有磁碟區都將計入進階資料保護的消耗，無論這些磁碟區是否鏡像。



== 臨時卷計費

有時， ONTAP在移動磁碟區時會建立臨時 (TMP) 磁碟區。這些臨時卷是短暫的，並且這些卷上的消耗不計入賬單。



== 計費和自適應 QoS 策略

Keystone根據服務水準來衡量消費。每個服務等級都與特定的自適應服務品質 (QoS) 策略相關聯。在部署期間，您將被告知所訂閱的Keystone服務的每個自適應 QoS 策略的詳細資訊。在儲存管理作業期間，請確保您的磁碟區根據您訂閱的服務等級分配了適當的自適應 QoS 策略，以避免意外計費。有關ONTAP中自適應 QoS 策略的更多信息，請參閱link:https://docs.netapp.com/us-en/ontap/performance-admin/guarantee-throughput-qos-task.html["透過QoS概述保證吞吐量"^]。



== SnapMirror目標計費

SnapMirror目標磁碟區的定價由來源上指派的服務等級的自適應 QoS 原則控制。但是，如果來源沒有關聯的自適應 QoS 策略，則目的地將根據最低可用服務等級進行計費。



== LUN 計費

對於 LUN，遵循與自適應 QoS 策略管理的磁碟區相同的計費模式。如果在 LUN 上設定了單獨的自適應 QoS 策略，則：

* LUN 的大小是根據該 LUN 的相關服務等級來計算消耗的。
* 卷中剩餘的空間（如果有）將根據磁碟區上設定的服務等級的自適應 QoS 策略進行收費。




== 系統捲和根卷

系統捲和根磁碟區作為Keystone服務整體監控的一部分進行監控，但不計算或計費。這些卷的消耗無需計費。
