---
sidebar: sidebar 
permalink: installation/install-itom-linux.html 
keywords: Linux installation, ITOM Collector installation 
summary: 在基於 Linux 的系統上安裝 ITOM Collector 軟體。 
---
= 在 Linux 系統上安裝 ITOM Collector
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
完成幾個步驟來安裝 ITOM Collector，它會收集您的儲存環境中的指標資料。根據您的要求，您可以在 Windows 或 Linux 系統上安裝它。


NOTE: Keystone支援團隊提供了一個動態連結來下載 ITOM Collector 安裝文件，該文件將在兩小時後過期。

若要在 Windows 系統上安裝 ITOM Collector，請參閱link:../installation/install-itom-windows.html["在 Windows 系統上安裝 ITOM Collector"]。

請依照以下步驟在 Linux 伺服器上安裝軟體：

.開始之前
* 驗證 Bourne shell 是否可用於 Linux 安裝腳本。
* 安裝 `vim-common`套件以取得 ITOM Collector 安裝檔案所需的 *xxd* 二進位。
* 確保 `sudo package`如果計劃以非 root 使用者身分執行 ITOM Collector，則安裝。


.步驟
. 將 ITOM 收集器安裝檔案下載到您的 Linux 伺服器。
. 在伺服器上開啟終端並執行以下命令來更改權限並使二進位檔案可執行：
`# chmod +x <installer_file_name>.bin`
. 運行命令啟動ITOM收集器安裝檔：
`#./<installer_file_name>.bin`
. 執行安裝檔會提示您：
+
.. 接受最終使用者授權協議 (EULA)。
.. 輸入安裝的使用者詳細資料。
.. 指定安裝父目錄。
.. 選擇收集器尺寸。
.. 如果適用，請提供代理詳細資訊。
+
對於每個提示，都會顯示一個預設選項。除非有特殊要求，建議選擇預設選項。按 *Enter* 鍵選擇預設選項。安裝完成後，會出現一則訊息確認 ITOM Collector 已成功安裝。





[NOTE]
====
* ITOM Collector 安裝檔新增了 `/etc/sudoers`處理服務重啟和記憶體轉儲。
* 在 Linux 伺服器上安裝 ITOM Collector 會建立一個名為 *ITOM* 的預設用戶，以在沒有 root 權限的情況下執行 ITOM Collector。您可以選擇其他使用者或以root身分執行，但建議使用Linux安裝腳本建立的ITOM使用者。


====
.下一步是什麼？
安裝成功後，請聯絡Keystone支援團隊透過 ITOM 支援入口網站驗證 ITOM Collector 是否安裝成功。驗證後， Keystone支援團隊將遠端配置 ITOM Collector，包括進一步的設備發現和監控設置，並在配置完成後發送確認。如有任何疑問或需要更多信息，請聯繫 keystone.services@netapp.com。
