---
sidebar: sidebar 
permalink: installation/linux-installation.html 
keywords: Linux installation Keystone, Linux Collector installation 
summary: 從 YUM 軟體儲存庫安裝Keystone Collector 軟體。 
---
= 在 Linux 系統上安裝Keystone Collector
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
您可以使用 RPM 或 Debian 套件在 Linux 伺服器上安裝Keystone Collector 軟體。根據您的 Linux 發行版執行安裝步驟。

[role="tabbed-block"]
====
.使用 RPM
--
. 透過 SSH 連接到Keystone Collector 伺服器並提升至 `root`特權。
. 導入Keystone公鑰簽章：
`# rpm --import https://keystone.netapp.com/repo/RPM-GPG-NetApp-Keystone-20221101`
. 透過檢查 RPM 資料庫中Keystone Billing Platform 的指紋，確保已匯入正確的公共憑證：
`# rpm -qa gpg-pubkey --qf '%{Description}'|gpg --show-keys --fingerprint`正確的指紋如下圖所示：
`90B3 83AF E07B 658A 6058 5B4E 76C2 45E4 33B6 C17D`
. 下載 `keystonerepo.rpm`文件：
`curl -O https://keystone.netapp.com/repo/keystonerepo.rpm`
. 驗證文件的真實性：
`rpm --checksig -v keystonerepo.rpm`真實文件的簽名如下圖所示：
`Header V4 RSA/SHA512 Signature, key ID 33b6c17d: OK`
. 安裝 YUM 軟體儲存庫檔案：
`# yum install keystonerepo.rpm`
. 安裝Keystone repo 後，透過 YUM 套件管理器安裝 keystone-collector 套件：
+
`# yum install keystone-collector`

+
對於 Red Hat Enterprise Linux 9，執行下列命令安裝 keystone-collector 套件：
`# yum install keystone-collector-rhel9`



--
.使用 Debian
--
. 透過 SSH 連接到Keystone Collector 伺服器並提升至 `root`特權。
`sudo su`
. 下載 `keystone-sw-repo.deb`文件：
`curl -O https://keystone.netapp.com/downloads/keystone-sw-repo.deb`
. 安裝Keystone軟體儲存庫檔案：
`# dpkg -i keystone-sw-repo.deb`
. 更新軟體包清單：
`# apt-get update`
. 安裝Keystone repo 後，安裝 keystone-collector 套件：
`# apt-get install keystone-collector`


--
====

NOTE: 完成安裝後，您可以使用Keystone Collector 管理終端使用者介面 (TUI) 公用程式執行設定和監控活動。您可以使用各種鍵盤控制（例如 Enter 和箭頭鍵）來選擇選項並瀏覽此 TUI。看link:../installation/configuration.html["配置Keystone收集器"]和link:../installation/monitor-health.html["監控系統健康狀況"]了解詳情。
