---
sidebar: sidebar 
permalink: installation/vapp-prereqs.html 
keywords: prerequisites, VMware vSphere, vApp 
summary: 在安裝Keystone Collector 之前，您的 VMware vSphere 系統必須滿足幾個要求。 
---
= 虛擬基礎架構要求
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
在安裝Keystone Collector 之前，您的 VMware vSphere 系統必須滿足幾個要求。

.Keystone Collector 伺服器虛擬機器的先決條件：
* 作業系統：VMware vCenter 伺服器和 ESXi 8.0 或更高版本
* 核心：1 個 CPU
* 記憶體：2 GB
* 磁碟空間：20 GB vDisk




== 其他要求

確保滿足以下通用要求：



=== 組網需求

Keystone Collector 的群組網路需求如下表所示。


NOTE: Keystone Collector 需要網路連線。您可以透過預設閘道（透過 NAT）直接路由或透過 HTTP 代理提供網際網路連線。這裡描述了這兩種變體。

|===


| 來源 | 目的地 | 服務 | 協定和連接埠 | 類別 | 目的 


 a| 
Keystone Collector（適用於Keystone ONTAP）
 a| 
Active IQ Unified Manager（統一管理器）
 a| 
HTTPS
 a| 
TCP 443
 a| 
強制（如果使用Keystone ONTAP）
 a| 
ONTAP的Keystone Collector 使用狀況指標收集



 a| 
Keystone Collector（用於Keystone StorageGRID）
 a| 
StorageGRID管理節點
 a| 
HTTPS
 a| 
TCP 443
 a| 
強制（如果使用Keystone StorageGRID）
 a| 
StorageGRID的Keystone Collector 使用狀況指標收集



 a| 
Keystone收集器（通用）
 a| 
互聯網（根據稍後給出的 URL 要求）
 a| 
HTTPS
 a| 
TCP 443
 a| 
強制性（網路連線）
 a| 
Keystone Collector 軟體、作業系統更新和指標上傳



 a| 
Keystone收集器（通用）
 a| 
客戶 HTTP 代理
 a| 
HTTP 代理
 a| 
客戶代理端口
 a| 
強制性（網路連線）
 a| 
Keystone Collector 軟體、作業系統更新和指標上傳



 a| 
Keystone收集器（通用）
 a| 
客戶 DNS 伺服器
 a| 
DNS
 a| 
TCP/UDP 53
 a| 
強制的
 a| 
DNS解析



 a| 
Keystone收集器（通用）
 a| 
客戶 NTP 伺服器
 a| 
NTP
 a| 
UDP 123
 a| 
強制的
 a| 
時間同步



 a| 
Keystone Collector（適用於Keystone ONTAP）
 a| 
統一管理器
 a| 
MYSQL
 a| 
TCP 3306
 a| 
選用功能
 a| 
Keystone Collector 的績效指標收集



 a| 
Keystone收集器（通用）
 a| 
客戶監控系統
 a| 
HTTPS
 a| 
TCP 7777
 a| 
選用功能
 a| 
Keystone Collector 健康報告



 a| 
客戶的操作工作站
 a| 
Keystone收集器
 a| 
SSH
 a| 
TCP 22
 a| 
管理
 a| 
造訪Keystone Collector Management



 a| 
NetApp ONTAP叢集和節點管理位址
 a| 
Keystone收集器
 a| 
HTTP_8000，PING
 a| 
TCP 8000，ICMP 回顯請求/答复
 a| 
選用功能
 a| 
用於ONTAP韌體更新的 Web 伺服器

|===

NOTE: 在全新安裝 Unified Manager 期間，MySQL 的預設連接埠 3306 僅限於本機，這會阻止收集Keystone Collector 的效能指標。有關更多信息，請參閱link:addl-req.html["ONTAP要求"] 。



=== URL 訪問

Keystone Collector 需要存取以下網際網路主機：

|===


| 地址 | 原因 


 a| 
https://keystone.netapp.com[]
 a| 
Keystone Collector 軟體更新與使用情況報告



 a| 
https://support.netapp.com[]
 a| 
NetApp HQ 用於帳單資訊和AutoSupport交付

|===