---
sidebar: sidebar 
permalink: release-notes/fixed-issues.html 
keywords: fixed issues 
summary: NetApp Keystone STaaS 服務先前版本中發現的問題已在後續版本中修復。 
---
= 已修正Keystone STaaS 中的問題
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp Keystone STaaS 服務先前版本中發現的問題已在後續版本中修復。

[cols="3*"]
|===
| 問題描述 | 修復後 | 已在發布中修復 


 a| 
Digital Advisor儀表板中配置了MetroCluster配置的訂閱的消費趨勢圖中缺少突發閾值線，顯示不正確的 *超出突發限制* 狀態。
 a| 
固定的
 a| 
2025年8月28日



 a| 
在「*Assets*」標籤中， StorageGRID的資產不可見。
 a| 
固定的
 a| 
2025年6月19日



 a| 
對於高級資料保護服務級別，在「消費趨勢」標籤中，圖表顯示了主站點和鏡像站點的分割。
 a| 
圖表不再顯示主站點和鏡像站點的分割。
 a| 
2025年6月19日



 a| 
當使用 Debian 軟體包安裝的現有Keystone Collector 嘗試透過Keystone Collector 管理 TUI 設定 HTTP 代理程式或啟用 Unified Manager 時，TUI 將變得無回應。
 a| 
固定的
 a| 
2025年5月19日



 a| 
由於缺少通用設置， Keystone Collector for StorageGRID無法正確配置。
 a| 
固定的
 a| 
2025年5月12日



 a| 
Keystone Collector 無法收集執行低於 9.11 版本的ONTAP叢集的使用量資料。
 a| 
固定的
 a| 
2025年4月30日



 a| 
連結訂閱的消費值顯示不正確的負數，導致總承諾使用量顯示不準確的高。
 a| 
固定的
 a| 
2025年4月14日



 a| 
無法在「消費趨勢」標籤中查看一些訂閱的服務等級的歷史資料。
 a| 
固定的
 a| 
2025年4月14日



 a| 
Digital Advisor儀表板上的 *Watchlist* 中缺少 * Keystone Subscriptions* 選項，*Reports* 中缺少 *Subscription Number* 選項。
 a| 
固定的
 a| 
2025年3月19日



 a| 
從Digital Advisor儀表板建立或修改監視清單後，*監視清單*中缺少一些Keystone訂閱。
 a| 
固定的
 a| 
2025年3月19日



 a| 
無法在「消費趨勢」標籤中查看與已過期且使用相同追蹤 ID 但不同服務等級續訂的訂閱相關的服務等級的歷史資料。
 a| 
固定的
 a| 
2025年3月19日



 a| 
從 * Keystone訂閱* 頁面上的 *訂閱* 標籤中選擇超過 10-12 個訂閱時，無法產生訂閱報告。
 a| 
固定的
 a| 
2025年1月8日



 a| 
對於 StorageGrid 訂閱，*磁碟區和物件*標籤中的*磁碟區摘要*子選項卡無法載入。
 a| 
固定的
 a| 
2024年11月21日



 a| 
當導覽至「*消費趨勢*」標籤時，「*起始日期*」欄位預設顯示未來日期，用於選擇日期範圍。
 a| 
固定的
 a| 
2024年9月4日



 a| 
設定 AQoS 策略時， Keystone Collector 管理 TUI 變成無回應。
 a| 
固定的
 a| 
2024年8月7日



 a| 
當從「*容量趨勢*」標籤中的「容量趨勢*」選項中選擇與目前日期對應的日期作為上個月的開始和結束日期時，使用情況圖表將顯示超出指定單日時間段的資料。
 a| 
使用情況圖表現在可以正確顯示指定單日期間的資料。
 a| 
2024年6月27日



 a| 
對於未配置MetroCluster配置的訂閱，*容量趨勢*標籤中的*CVO Primary* 和 *CVO Secondary* 服務等級不提供歷史累計突發資料。
 a| 
固定的
 a| 
2024年6月21日



 a| 
AutoSupport訂閱的「磁碟區詳細資料」標籤上所列的物件儲存消耗值顯示不正確。
 a| 
物件儲存的消耗值現在可以正確顯示。
 a| 
2024年6月21日



 a| 
無法在使用MetroCluster配置配置的AutoSupport訂閱的 *Assets* 標籤中查看叢集層級資訊。
 a| 
固定的
 a| 
2024年6月21日



 a| 
如果從「容量趨勢」標籤產生的 CSV 報表中的「帳戶名稱」欄位包含有逗號的帳號名稱，則Keystone資料會在 CSV 報表中錯位 `(,)`。
 a| 
Keystone資料在 CSV 報告中正確對齊。
 a| 
2024年5月29日



 a| 
即使消耗量低於承諾的容量，也可以從「容量趨勢」標籤顯示累計突發使用量。
 a| 
固定的
 a| 
2024年5月29日



 a| 
*容量趨勢*選項卡中的*目前突發*索引圖示的工具提示文字不正確。
 a| 
顯示正確的工具提示文字「_目前正在消耗的突發容量量。請注意，這是針對目前結算期，而不是選定的日期範圍。 _”
 a| 
2024年3月28日



 a| 
如果Keystone資料在 24 小時內不存在，則AutoSupport訂閱將無法提供有關 AQoS 不相容磁碟區和MetroCluster合作夥伴的資訊。
 a| 
固定的
 a| 
2024年3月28日



 a| 
如果為僅滿足一個服務級別的 AQoS 合規性的捲分配了兩個服務級別，則“*卷摘要*”和“*卷詳細信息*”選項卡上列出的 AQoS 不合規卷的數量偶爾會不匹配。
 a| 
固定的
 a| 
2024年3月28日



 a| 
AutoSupport訂閱的「*資產*」標籤上沒有可用資訊。
 a| 
固定的
 a| 
2024年3月14日



 a| 
如果在分層和物件儲存的費率計劃均適用的環境中同時啟用MetroCluster和FabricPool ，則可能會錯誤地得出鏡像磁碟區（組成磁碟區和FabricPool磁碟區）的服務等級。
 a| 
正確的服務等級已套用於鏡像磁碟區。
 a| 
2024年2月29日



 a| 
對於某些具有單一服務等級或費率方案的訂閱，「*Volumes*」標籤所報告的 CSV 輸出中缺少 AQoS 合規性欄位。
 a| 
合規性列在報告中可見。
 a| 
2024年2月29日



 a| 
在某些MetroCluster環境中，在「效能」標籤中的 IOPS 密度圖表中偶爾偵測到異常。這是由於磁碟區與服務等級的映射不準確所造成的。
 a| 
圖表顯示正確。
 a| 
2024年2月29日



 a| 
突發消費記錄的使用情況指示燈顯示為琥珀色。
 a| 
指示器顯示為紅色。
 a| 
2023年12月13日



 a| 
容量趨勢、目前使用情況和效能標籤中的日期範圍和資料未轉換為 UTC 時區。
 a| 
所有標籤中的查詢和資料的日期範圍均以 UTC 時間（伺服器時區）顯示。選項卡上的每個日期欄位也顯示 UTC 時區。
 a| 
2023年12月13日



 a| 
選項卡和下載的 CSV 報告之間的開始日期和結束日期不符。
 a| 
固定的。
 a| 
2023年12月13日

|===